# dqn_ae_config.yaml

env:
  name: CarRacing-v3
  frame_stack: 1

seed: 0

agent:
  latent_dim: 32
  encoder_weights_path: autoencoder/models/autoencoder.pth

  buffer_capacity:    100000
  batch_size:         64
  learning_rate:      0.0005
  gamma:              0.99
  epsilon_start:      1.0
  epsilon_final:      0.1
  epsilon_decay:      10000
  target_update_freq: 1000

  save_path: models/dqn_with_ae.pt

train:
  num_frames:     100000
  eval_interval:  1000